import numpy

import ase
import tsase 

def write_lammps(filename, atoms):
    f = open(filename, 'w')
    f.write(' lammps data file generated by tsase\n\n')
    f.write(' %d atoms\n\n' % len(atoms))
    symbols = atoms.get_chemical_symbols()
    elements = list(set(symbols))
    elements.sort()
    f.write(' %d atom types\n\n' % len(elements))
    f.write(' 0.0 %12.6f xlo xhi\n' % atoms.cell[0][0])
    f.write(' 0.0 %12.6f ylo yhi\n' % atoms.cell[1][1])
    f.write(' 0.0 %12.6f zlo zhi\n\n' % atoms.cell[2][2])
    f.write(' Masses\n\n')
    for i in range(len(elements)):
        f.write(' %d %12.6f\n' % (i+1, tsase.data.elements[elements[i]]['mass']))
    f.write('\n')
    f.write(' Atoms\n\n')
    for i in range(len(atoms)):
        typ = elements.index(symbols[i]) + 1
        r = atoms[i].position
        f.write(' %d %d %12.6f %12.6f %12.6f\n' % (i+1, typ, r[0], r[1], r[2]))
    f.write('\n')
    f.write(' Velocities\n\n')
    for i in range(len(atoms)):
        f.write(' %d 0.0 0.0 0.0\n' % (i+1))
    f.close()
    
if __name__ == '__main__':
    import sys
    p = tsase.io.read(sys.argv[1])
    write_lammps(sys.argv[1] + '.lammps', p)
    
    
    
