all:
	cd al/code && $(MAKE)
	cd morse/code && $(MAKE)
	cd lj/code && $(MAKE)
al:
	cd al/code && $(MAKE)
morse:
	cd morse/code && $(MAKE)
lj:
	cd lj/code && $(MAKE)

.PHONY: clean
clean:
	cd al/code && $(MAKE) clean
	cd morse/code && $(MAKE) clean
	cd lj/code && $(MAKE) clean

